default: &default
  adapter: postgresql
  host: localhost
  username: ads
  password: 123
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: avdb1_development

test:
  <<: *default
  database: avdb1_test

production:
  <<: *default
  database: avdb1_production
